### ISSUE TITLE
Please provide `ShowCaseView` context

### ISSUE THREAD

**Issue by enricobenedos** [SimformSolutionsPvtLtd/flutter_showcaseview#324]
**Describe the bug**
Unable to keep this package working due to error "Please provide ShowCaseView context". I was looking for a solution sifting through the closed issues on the repo but it seems that there are no consistent solutions.

**To Reproduce**
I simplified the implementation that is causing the issue. In this case I'm using `google_maps_flutter` package.
```dart
class GoogleMapsPage extends StatefulWidget {
  final int tourId;
  final List<TraceCoordinate> coordinates;
  final List<TourMarker>? markers;

  const GoogleMapsPage(
      {Key? key})
      : super(key: key);

  @override
  State<GoogleMapsPage> createState() => _GoogleMapsPageState();
}

class _GoogleMapsPageState extends State<GoogleMapsPage>
    with WidgetsBindingObserver {
  final GlobalKey _introStep1 = GlobalKey();
  final GlobalKey _introStep2 = GlobalKey();
  final GlobalKey _introStep3 = GlobalKey();
  final GlobalKey _introStep4 = GlobalKey();
  final GlobalKey _introStep5 = GlobalKey();

  Widget _panelWidget = const SizedBox();

  @override
  void initState() {
    super.initState();

    //Observer needed to use the didChangeAppLifecycleState override
    WidgetsBinding.instance.addObserver(this);

    WidgetsBinding.instance.addPostFrameCallback((_) =>
        ShowCaseWidget.of(context).startShowCase(
            [_introStep1, _introStep2, _introStep3, _introStep4, _introStep5]));
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ShowCaseWidget(
      builder: Builder(
        builder: (context) => WillPopScope(
          onWillPop: () async {
            debugPrint('Map tutorial finished');

            await MySharedPreferences.setMapTutorialShowed(true);
            return true;
          },
          child: Scaffold(
            appBar: WamiiAppBar(
              avoidIconOverride: true,
              actions: [
                _showPermissionsWarning
                    ? const LocationPermissionsWarningButton()
                    : const SizedBox(),
              ],
            ),
            body: WamiiSlidingUpPanel(
              panelController: _panelController,
              onPanelOpened: () => setState(() => _canShowFAB = false),
              onPanelClosed: () => setState(() => _canShowFAB = true),
              onPanelSlide: (double slideValue) =>
                  setState(() => _canShowFAB = false),
              body: Stack(
                children: [
                  Center(
                    child: Showcase(
                      key: _introStep4,
                      description: AppLocalizations.of(context)
                          .translate('maps_tutorial_4'),
                      child: const SizedBox(),
                    ),
                  ),
                  Center(
                    child: Showcase(
                      key: _introStep5,
                      description: AppLocalizations.of(context)
                          .translate('maps_tutorial_5'),
                      child: const SizedBox(),
                    ),
                  ),
                  GoogleMap(
                    myLocationEnabled: true,
                    compassEnabled: false,
                    mapToolbarEnabled: false,
                    tiltGesturesEnabled: false,
                    initialCameraPosition: CameraPosition(
                        zoom: cameraZoom,
                        bearing: cameraBearing,
                        tilt: cameraTilt,
                        target: sourceLocation),
                    myLocationButtonEnabled: false,
                    zoomControlsEnabled: false,
                  ),
                  Positioned(
                    left: -11,
                    top: 5,
                    child: Column(
                      children: [
                        Showcase(
                          key: _introStep2,
                          description: AppLocalizations.of(context)
                              .translate('maps_tutorial_3'),
                          child: RawMaterialButton(
                            onPressed: () { },
                            fillColor: Colors.white60,
                            shape: const CircleBorder(),
                            child: const Icon(
                              Icons.layers,
                              size: 20.0,
                              color: Colors.black,
                            ),
                          ),
                        ),
                        Showcase(
                          key: _introStep3,
                          description: AppLocalizations.of(context)
                              .translate('maps_tutorial_3'),
                          child: RawMaterialButton(
                            onPressed: () async {},
                                  ),
                                  confirmTextOverride:
                                      AppLocalizations.of(context)
                                          .translate('filter_markers'),
                                  rejectTextOverride:
                                      AppLocalizations.of(context)
                                          .translate('reset_filters'),
                            onConfirm: () {}, 
                            onReject: () {},
                            fillColor: Colors.white60,
                            shape: const CircleBorder(),
                            child: Icon(
                              Icons.place,
                              size: 20.0,
                              color: _filteredMarkers.isNotEmpty
                                  ? Colors.orange
                                  : Colors.black,
                            ),
                          ),
                        )
                      ],
                    ),
                  )
                ],
              ),
              panel: Padding(
                padding: const EdgeInsets.all(15.0),
                child: _panelWidget,
              ),
            ),
            floatingActionButton: Visibility(
              visible: _canShowFAB,
              child: Showcase(
                key: _introStep1,
                description:
                    AppLocalizations.of(context).translate('maps_tutorial_1'),
                child: FloatingActionButton.extended(
                  onPressed: () {},
                  label: Text(AppLocalizations.of(context)
                      .translate('go_to_tour_start')),
                  icon: const Icon(FontAwesomeIcons.signsPost),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Expected behavior**
`ShowCaseWidget` is the main widget of my page and contains all the widgets that needs to render the page so it can be defined the all page widgets "parent".

**Additional context**
```
════════ Exception caught by scheduler library ═════════════════════════════════
The following _Exception was thrown during a scheduler callback:
Exception: Please provide ShowCaseView context

When the exception was thrown, this was the stack
#0      ShowCaseWidget.of
package:showcaseview/src/showcase_widget.dart:110
#1      _GoogleMapsPageState.initState.<anonymous closure>
package:wamii_app/…/tour_subpages/google_maps_page.dart:70
#2      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#3      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1113
#4      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#5      _invoke (dart:ui/hooks.dart:148:13)
#6      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#7      _drawFrame (dart:ui/hooks.dart:115:31)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by ujas-m-simformsolutions** [comment]
Hey @enricobenedos, You need to add `ShowCaseWidget` at one more level above. You are using `Showcase.of(context)` inside initState but ShowCaseWidget is initialized in the same widget's build method. So wherever you are using `GoogleMapsPage` just wrap it with ShowCaseWidget, and it should work.

**Comment by enricobenedos** [comment]
Hello @ujas-m-simformsolutions, thanks for your explanation, I'll apply it. Anyway I'm confused about 

> You are using Showcase.of(context) inside initState but ShowCaseWidget is initialized in the same widget's build method

That is right, `ShowCaseWidget` is initialized in `build` method, then after first build execution (`ShowCaseWidget` rendered) the framework, thanks to `addPostFrameCallback` call `startShowCase`. In this moment I expect that context is known by `ShowCaseWidget`.

**Comment by ujas-m-simformsolutions** [comment]
@enricobenedos The error is not thrown due to context not being accessible. You can try adding some 5-10 seconds of delay for showing showcase and it will still throw error. The error is thrown because ShowcaseWidget basically an `Inherited widget` and by using Showcase.of(context), you are accessing it's functions but Inherited widget need to be declared at top level before it gets used. You can think of it as some type of `Provider` package implementation. Provider is also an inherited widget but it just simplifies the api.

You can find more on Inherited widget [here](https://api.flutter.dev/flutter/widgets/InheritedWidget-class.html).

**Comment by enricobenedos** [comment]
Anyway I've solved the issue with your advice, thanks.
