### ISSUE TITLE
Exception:BoxConstraints has NaN values

### ISSUE THREAD

**Issue by ShengjieGeng** [SimformSolutionsPvtLtd/flutter_showcaseview#78]
Hi,My first Flutter APP is using showcaseview widget
here is my code
```
Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              Showcase.withWidget(
                key: _myBook,
                width: 300,
                height: 350,
                container: Card(
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(8, 10, 8, 10),
                    child: Text('小迪阅读过的绘本都\n会在这里看到哦!'),
                  ),
                ),
                child: Icon(Icons.favorite),
   )])
```

,But I got some trouble,the console print some log 
![image](https://user-images.githubusercontent.com/18364968/98206585-1e9a5e80-1f75-11eb-87bc-e69d0b9cdc3a.png)

please do me a favor, thanks a lot!
below is the sdk version I'm using: 
![image](https://user-images.githubusercontent.com/18364968/98206868-aaac8600-1f75-11eb-8d95-68a4dc0f3182.png)

**Comment by BirjuVachhani** [comment]
@ShengjieGeng It seems that this is not related to `ShowcaseView`.

**Comment by BirjuVachhani** [comment]
@ShengjieGeng AFAIK, you cannot put `ShowcaseView` as part of your widget tree directly.

**Comment by DevarshRanpara** [comment]
@ShengjieGeng Can you share file that contains this code?

**Comment by ShengjieGeng** [comment]
Sorry，I finally give up the ShowcaseView.
then everything is fine.
I will check the widget again after uploading the app to the store.

**Comment by jlepocher** [comment]
Having the same issue since using the `showcaseview` package.

That seems to happen every time a widget which contains a `ShowCaseWidget` is rebuilt in the background (while it is not at the top of the stack).

**Comment by ikicodedev** [comment]
Having the same issue. Any alternative workaround?

**Comment by Abdox3** [comment]
Happens with me if I use navigation bar tabs to navigate

**Comment by adriancsbna** [comment]
Having the same issue.

**Comment by realkimmy** [comment]
same issue

**Comment by vatsaltanna** [comment]
Hello guys, 

can anyone please provide reproducible steps with a code snippet for this issue?

Thanks.

**Comment by alocus** [comment]
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23636): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23636): The following assertion was thrown building Container(bg: ShapeDecoration(shape:
I/flutter (23636): CircleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none))), constraints:
I/flutter (23636): BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED), dirty):
I/flutter (23636): BoxConstraints has NaN values in minWidth, maxWidth, minHeight, and maxHeight.
I/flutter (23636): The offending constraints were:
I/flutter (23636):   BoxConstraints(NaN<=w<=NaN, NaN<=h<=NaN; NOT NORMALIZED)
I/flutter (23636):
I/flutter (23636): The relevant error-causing widget was:
I/flutter (23636):   Container
I/flutter (23636):
lib/…/src/showcase.dart:323
I/flutter (23636):
I/flutter (23636): When the exception was thrown, this was the stack:
I/flutter (23636): #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError
package:flutter/…/rendering/box.dart:517
I/flutter (23636): #1      BoxConstraints.debugAssertIsValid.<anonymous closure>
package:flutter/…/rendering/box.dart:541
I/fl


<img width="1090" alt="Screen Shot 2021-07-10 at 12 38 25 AM" src="https://user-images.githubusercontent.com/7285594/125152342-fa051080-e119-11eb-8783-629306cad829.png">

The problem is Offset object has NaN dx and dy.  So my "kludge" is to not build the showcase when Offset(Offset (NaN, NaN)).


Here is my observation about the problem that I have encounter:
1.  I have a navigation bar at the bottom where I have 3 pages (Home, Upload, Profile)
2.  The app lands on Home page
3.  Showcase is configured on Upload page
4.  There is a list of actions on the Appbar on Profile page

If I launch the app, it lands on Home, then go directly to Profile page.  During init state of Profile page, it triggers the showcase on Upload page, this is where the Offset is NaN.   For my app, if I removed (4), the actions on the Appbar of Profile page, the app doesn't crash.  So I am not sure why the actions bar trigger the showcase on the Upload page 

I am still not sure the root cause as I can't build a demo app to trigger this issue.  So I kludge it my way.

**Comment by jgadsby** [comment]
I can confirm that this trick works @alocus, but I hope it can be fixed in the main library soon.

**Comment by alocus** [comment]
@vatsaltanna-simformsolutions can you please have a look at the comments above to see if you can understand why Offset(NaN, NaN) could happen or put a similar check as above to prevent showcaseview from crashing?

**Comment by vatsaltanna** [comment]
Thanks, @alocus for the detailed description, we will check the configuration asap and will update here as soon as I get any updates from my Team.

**Comment by vatsaltanna** [comment]
Hi @alocus @jgadsby, We weren't able to reproduce this issue. could you please help us by providing a sample code in which this issue is reproducible?

Steps we have followed to reproduce the issue:
1. we added three pages.
2. the second page has a showcase view.
3. the third page has an app bar with actions.
4. on the app start we first page was displayed.
5. we redirected to the third page with animateToPage function.
6. and it didn't crash, it worked as expected.

Do let us know if any of the steps we have forgotten to reproduce the issue.

**Comment by alocus** [comment]
@vatsaltanna-simformsolutions thanks for attempting to reproduce the problem.  Unfortunately, I couldn't create a simple demo app neither.  What you did was exactly how my app was build, so it is possible that I missed something.   Nonetheless another clue from above comment is 

"That seems to happen every time a widget which contains a ShowCaseWidget is rebuilt in the background (while it is not at the top of the stack)."  from @jlepocher 

The problem I encountered seems to align with this observation.  I am just not able to find the root cause, so that's why I kluge it to catch the Offset (NaN, NaN) case to not build showcasewidget.

**Comment by vatsaltanna** [comment]
Thanks for the information @alocus, we will try with some different edge cases to reproduce this issue, even after that if it will still causing an issue then we will go with the safe side of NaN check.

**Comment by Knackynouille** [comment]
Hello,
Is there any news regarding this issue ?
I also have this problem. 
I have an application with three pages.
In the first page I use ShowCaseView.
In the second page I have a button to navigate to another screen (which contains calls to the ShowCaseView plugins). When i navigate i have this error.
When the exception was thrown, this was the stack: 
```
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:541:9)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2394:27)
#4      Container.build (package:flutter/src/widgets/container.dart:428:17)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4739:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#8      StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#17     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#21     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#31     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#33     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5700:32)
#34     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6356:17)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#40     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5020:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#48     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#54     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#55     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#56     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#57     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#58     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#62     _invoke (dart:ui/hooks.dart:166:10)
#63     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#64     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)
```
Without the reference to the ShowCaseView plugin I don't have this error.

**Comment by alocus** [comment]
Hello @Knackynouille,

Are you using "animateToPage" or "jumpToPage" when you navigate?  If it is "animateToPage", then please try "jumpToPage" instead.   I have a theory, but haven't confirmed.  If you have these page structure: Page 1, Page 2, Page 3 and Page 2 has showcaseview.  When you navigate from Page 1 to Page 3 with animateToPage, it will show Page 2 as part of the animation before reaching Page 3.    Page 2 get created and deconstructed by flutter quickly, and showcaseview got created while Page 2 is being removed, thus causes the problem.

**Comment by Knackynouille** [comment]
Hello,
@alocus
I try this tommorow if i have the time !

But I don't think the problem comes from there.
Indeed I have the problem if:
On my page 1 I have a ShowCaseWidget.
The application launches and come on page 1 (The ShowCaseWidget is displayed).
I go to my page two.
I click a button to navigate to another view that contains a ShowCaseView.
The error appears.
If I did return to page 2.
The error appears again.

I could try to make a snippet if I really have time next week

**Comment by meetjanani** [comment]
@Knackynouille  & @alocus  Thank you for providing more details. it helps to reproduce this,
It is in Progress and we will update here as soon as there will be any progress on this.

**Comment by Knackynouille** [comment]
@meetjanani Do you have find the bug ? Or i will try to create a sinppet
