### ISSUE TITLE
Can't use Showcase on Bottom Navigation Items

### ISSUE THREAD

**Issue by Zony-Zhao** [SimformSolutionsPvtLtd/flutter_showcaseview#96]
**Describe the bug**
Page crashes when I wrap Showcase around BottomNavigationItem icons.
![image](https://user-images.githubusercontent.com/50739849/111100736-5a78ac80-8583-11eb-8aaf-2b7276cd875a.png)

**To Reproduce**
Simply wrap Showcase around the Icon
![image](https://user-images.githubusercontent.com/50739849/111100870-af1c2780-8583-11eb-9d64-ef4abf7ef993.png)

**Error**
The following NoSuchMethodError was thrown building IconTheme(color: Color(0x8a000000), size: 24.0):
The getter 'activeWidgetIds' was called on null.
Receiver: null
Tried calling: activeWidgetIds

The relevant error-causing widget was: 
  BottomNavigationBar file:///E:/_project/flutter/upper_bunk_bro_frontend/lib/routes/tabs/HomePage.dart:92:30
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      ShowCaseWidget.activeTargetWidget (package:showcaseview/showcase_widget.dart:51:10)
#2      _ShowcaseState.showOverlay (package:showcaseview/showcase.dart:171:43)
#3      _ShowcaseState.didChangeDependencies (package:showcaseview/showcase.dart:164:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4653:11)

**Additional context**
Android simulator.

**Comment by PannagaShetty** [comment]
did anyone get the solution for this

**Comment by bobykurniawan11** [comment]
I'm using packages for this `https://pub.dev/packages/persistent_bottom_nav_bar`

**Comment by vatsaltanna** [comment]
Hello @Zony-Zhao @PannagaShetty , I tried to reproduce the issue as you said in the description. but I wasn't able to replicate it. it works fine for me when I used showcase view for icons in the bottom navigation bar. it will be much more helpful If you can provide more code snippets in which you are facing this issue.

**Comment by vatsaltanna** [comment]
I am closing this issue because of no activity. Please feel free to reopen this if it is still happening.

**Comment by abdullah432** [comment]
@vatsaltanna how to show description box above Bottom Navigation Bar instead at the bottom?

**Comment by vatsaltanna** [comment]
@abdullah432 it will display description box on top automatically when there is no space to display in bottom. You can check floating action button in the example project of repository it has the same kind of behaviour.

**Comment by romreed** [comment]
![Simulator Screen Shot - iPhone X - 2021-09-09 at 17 45 46](https://user-images.githubusercontent.com/16118227/132707685-2cd04672-eaf2-4445-969a-71c82d7f9f74.png)
![Simulator Screen Shot - iPhone X - 2021-09-09 at 17 45 48](https://user-images.githubusercontent.com/16118227/132707711-0b6e0e49-d960-49e3-9c80-97805c07f6f9.png)

**Comment by samatzhusup** [comment]
откуда icon pack?)
