### ISSUE TITLE
Crash in the library

### ISSUE THREAD

**Issue by achinverma** [SimformSolutionsPvtLtd/flutter_showcaseview#98]
Hi, i am using this library in my code and i am getting below error in my code.

```
The following NoSuchMethodError was thrown building ToolTipWidget(dirty, state:
I/flutter ( 5689): _ToolTipWidgetState#e6d4b):
I/flutter ( 5689): The getter 'length' was called on null.
I/flutter ( 5689): Receiver: null
I/flutter ( 5689): Tried calling: length
I/flutter ( 5689): 
I/flutter ( 5689): The relevant error-causing widget was:
I/flutter ( 5689):   MaterialApp file:///C:/Users/Signity/Documents/projects/my-ambar/lib/main.dart:164:12
I/flutter ( 5689): 
I/flutter ( 5689): When the exception was thrown, this was the stack:
I/flutter ( 5689): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 5689): #1      _ToolTipWidgetState._getTooltipWidth (package:showcaseview/tooltip_widget.dart:91:51)
I/flutter ( 5689): #2      _ToolTipWidgetState._getRight (package:showcaseview/tooltip_widget.dart:130:42)
I/flutter ( 5689): #3      _ToolTipWidgetState.build (package:showcaseview/tooltip_widget.dart:185:20)
I/flutter ( 5689): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter ( 5689): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter ( 5689): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 5689): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter ( 5689): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
I/flutter ( 5689): #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter ( 5689): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter ( 5689): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 5689): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter ( 5689): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 5689): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter ( 5689): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 5689): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter ( 5689): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 5689): #28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 5689): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter ( 5689): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #32     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
I/flutter ( 5689): #33     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter ( 5689): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter ( 5689): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter ( 5689): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter ( 5689): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter ( 5689): #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter ( 5689): #39     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter ( 5689): #40     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter ( 5689): #41     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter ( 5689): #42     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter ( 5689): #43     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter ( 5689): #47     _invoke (dart:ui/hooks.dart:251:10)
I/flutter ( 5689): #48     _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter ( 5689): (elided 3 frames from dart:async)
```

**Comment by BirjuVachhani** [comment]
@achinverma Could you please add the code that is throwing this as well?

**Comment by vatsaltanna** [comment]
@achinverma Does this still happen for you in the latest version?

**Comment by achinverma** [comment]
> @achinverma Does this still happen for you in the latest version?

yes

**Comment by vatsaltanna** [comment]
Could you please provide a widget snippet where you used the showcase view and also the latest stack trace of the crash?

**Comment by vatsaltanna** [comment]
Due to less information, I am closing this issue. Feel free to reopen this issue in case if it is still happing.
